### ISSUE TITLE
MLflow Artifacts error

### ISSUE THREAD

**Issue by micron1390** [aganse/docker_mlflow_db#5]
Hello,
Could you tell me please how to configure MLflow Local storage according to the guide:
[mlflow-storage](https://mlflow.org/docs/latest/tracking.html#scenario-1-mlflow-on-localhost)

I added it to docker-compose:
```
    app:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        expose:
            - 5001
        # networks:
        #     - frontend
        #     - backend
        environment:
          - BACKEND=postgresql://${DB_USER:-postgres}@${DB_SERVER:-db}:${DB_PORT:-5432}/${DB_NAME:-mlflow}
          - ARTIFACTS=/storage/mlruns  # in-container path to filestore in filesys
          # For artifact store in AWS S3 (uses boto that was installed in container):
          # Commment out ARTIFACTS line above and instead use:
          #  - ARTIFACTS="s3://mlflow_bucket/my_mlflow_dir/"
          #  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          #  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          #  - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        volumes:
            - ${FILESTORE:-/storage/mlruns}:/storage/mlruns  # can comment out this line if using S3
            - ${PGPASS:-~/.pgpass}:/root/.pgpass  # provides the pw for BACKEND database
            - condaenv_vol:/opt/conda  # provides continuity/speed when looping runs with same container
        command:
            - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
            - -c
            - mlflow server
                --port 5001
                --host 0.0.0.0
                --backend-store-uri $${BACKEND}
                --default-artifact-root $${ARTIFACTS}
                --app-name basic-auth

``` 
but artifacts are not written to local storage

Thanks in advance for your advice and suggestions.
